#TOTVS | License Server Virtual (x64)

#TargetPanel_2
INSTALL_PATH=/totvs/totvslicensevirtual

#installationtype
LICENSE_INSTALL=install

#appserverconfig
SERVICE_PORT=2235
LOG_PORT=4000
LICENSE_PORT=5555
SERVICE_NAME=licenseVirtual

#proxyconfig
PROXY_ENABLE=0
PROXY_SERVER=
PROXY_PORT=
PROXY_USER=
PROXY_PASSWORD=
